services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  sensor:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    container_name: sensor-apac
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: always
