services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  sensor:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    container_name: sensor-publisher
    depends_on:
      - mosquitto
    volumes:
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
      - APP_TIMEZONE=America/Maceio
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=iot/chuva
      - MQTT_RETAIN=true
      - INITIAL_PUBLISH_INTERVAL_SECONDS=0
      - PUBLISH_INTERVAL_SECONDS=5
      - OPEN_METEO_TIMEOUT_SECONDS=3
      - CITY_NAME=Maceió
      - STATE_NAME=Alagoas
      - COUNTRY_NAME=Brasil
      - OVERPASS_URL=https://overpass-api.de/api/interpreter
      - NEIGHBORHOOD_CACHE_FILE=/app/cache/neighborhoods_cache.json
      - REFRESH_NEIGHBORHOODS_ON_START=false
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
      - APP_TIMEZONE=America/Maceio
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=iot/chuva
    restart: always
