FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard_web.py .
COPY ia_model.py .

EXPOSE 8501

CMD ["streamlit", "run", "dashboard_web.py", "--server.address=0.0.0.0"]
